In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from tqdm import tqdm,tnrange
from SD import stochastic_descent
import numpy as np

'''from quantum_state import i,hamiltonian_LA
from quantum_state import i, evolution_from_protocol, spectral_time_evolution, compute_fidelity
from qutip import basis, Bloch
from gif import qutip_qstate
from Qmodel import quantum_model
'''

import os
import pandas as pd

## STRANA SIMMETRIA CHE SPUTTANA DIM H, PRESENTE SIA IN KEPIZZA SIA NEL TUTORIAL BASE DI QUSPIN
#### PROBLEMA kblock=0,pblock=1


In [68]:
from quspin.operators import hamiltonian
from quspin.basis import spin_basis_1d
def hamitonian(L=2 , J=1.0, hz = 1.0, hx_min=-4., hx_max =4., dh=2., n_step=1, symm =True ,**kwargs): # N is the number of time steps
    #basis = spin_basis_1d(L=L,pauli=False)
    fct_arg=[]
    ones=[[-1,i] for i in range(L)]
    z_field=[[-hz,i] for i in range(L)]

    if L>1:
        if symm is True:
            basis = spin_basis_1d(L=L,pauli=False,kblock=0,pblock=1) # include symmetries (momentum and parity sectors)
        else:
            basis = spin_basis_1d(L=L,pauli=False) # w/o symmetries

        zz_int =[[-J,i,(i+1)%L] for i in range(L)] # Has periodic boundary conditions
        static = [["zz",zz_int], ["z",z_field]]
    else:
        basis = spin_basis_1d(L=L,pauli=False) # w/o symmetries (momentum and parity sectors)
        static = [["z", z_field]]


    h_set = compute_h_set(hx_min,hx_max,dh) # discrete set of possible h fields 
    hx_discrete = np.zeros(n_step, dtype=int) # hx_discrete are protocols specified as integers

    fct = lambda time: h_set[hx_discrete[int(time)]] # time takes discrete values in our problem
    fct_cont = lambda h: h # trick : when calling the time - will instead interpret it as a field value 

    dynamic_discrete = [["x", ones, fct, fct_arg]]
    dynamic_cont = [["x", ones, fct_cont, fct_arg]]

    kwargs = {'dtype':np.float64,'basis':basis,'check_symm':False,'check_herm':False,'check_pcon':False}

    basis = basis
    hamiltonian_discrete = hamiltonian(static, dynamic_discrete, **kwargs)
    hamiltonian_cont = hamiltonian(static, dynamic_cont, **kwargs)
    print(hamiltonian_cont(time = 4).todense())

def ground_state(hx = 0.):
    return hamiltonian_cont.eigsh(time=hx, k=1, which='SA')[1]

def eigenvalue(hx = 0.):
    """ Returns the spectrum of the Hamiltonian for a specific value of the transverse field """
    return hamiltonian_cont.eigvalsh(time=hx)

def eigen_basis(hx = 0.):
    """ Returns the eigenbasis of the Hamiltonian for a specific value of the transverse field """
    return hamiltonian_cont.eigh(time=hx)

def compute_h_set(hmin, hmax, dh):
    """ Computes the different values of hx given the maximum and minimum values specified by the user """
    return np.arange(hmin, hmax+1e-6, dh)

def update_hx(time=0, hx = None, hx_idx = None):
    """ Updates the protocol hx(t) at time t. The new value is hx.
    One can either specify a scalar value for the hx field. Another option
    is to use the integer index for the field. Since we are hx can take only
    a discrete set of values between hmin and hmax, those values can are also indexed by integers
    """
    if hx_idx is not None:
        hx_discrete[time]=hx_idx
    elif hx is not None:
        idx = np.argmin(np.abs(h_set-hx))
        hx_discrete[time] = idx
    else:
        assert False, "Error in update_hx in Hamiltonian class"

def evaluate_H_at_hx(hx = 0.):
    """ Returns the full hamiltonian evaluated at global transverse field hx """
    return hamiltonian_cont(time = hx)

hamitonian()

[[-1.5        -2.82842712  0.        ]
 [-2.82842712  0.5        -2.82842712]
 [ 0.         -2.82842712  0.5       ]]


## HAMILTONIANA CHE MI ASPETTO

In [67]:
from quspin.operators import hamiltonian
from quspin.basis import spin_basis_1d
def hamitonian(L=2 , J=1.0, hz = 1.0, hx_min=-4., hx_max =4., dh=2., n_step=1, symm =True ,**kwargs): # N is the number of time steps
    #basis = spin_basis_1d(L=L,pauli=False)
    fct_arg=[]
    ones=[[-1,i] for i in range(L)]
    z_field=[[-hz,i] for i in range(L)]

    if L>1:
        if symm is True:
            basis = spin_basis_1d(L=L,pauli=False) # include symmetries (momentum and parity sectors)
        else:
            basis = spin_basis_1d(L=L,pauli=False) # w/o symmetries

        zz_int =[[-J,i,(i+1)%L] for i in range(L)] # Has periodic boundary conditions
        static = [["zz",zz_int], ["z",z_field]]
    else:
        basis = spin_basis_1d(L=L,pauli=False) # w/o symmetries (momentum and parity sectors)
        static = [["z", z_field]]


    h_set = compute_h_set(hx_min,hx_max,dh) # discrete set of possible h fields 
    hx_discrete = np.zeros(n_step, dtype=int) # hx_discrete are protocols specified as integers

    fct = lambda time: h_set[hx_discrete[int(time)]] # time takes discrete values in our problem
    fct_cont = lambda h: h # trick : when calling the time - will instead interpret it as a field value 

    dynamic_discrete = [["x", ones, fct, fct_arg]]
    dynamic_cont = [["x", ones, fct_cont, fct_arg]]

    kwargs = {'dtype':np.float64,'basis':basis,'check_symm':False,'check_herm':False,'check_pcon':False}

    basis = basis
    hamiltonian_discrete = hamiltonian(static, dynamic_discrete, **kwargs)
    hamiltonian_cont = hamiltonian(static, dynamic_cont, **kwargs)
    print(hamiltonian_cont(time = 4).todense())

def ground_state(hx = 0.):
    return hamiltonian_cont.eigsh(time=hx, k=1, which='SA')[1]

def eigenvalue(hx = 0.):
    """ Returns the spectrum of the Hamiltonian for a specific value of the transverse field """
    return hamiltonian_cont.eigvalsh(time=hx)

def eigen_basis(hx = 0.):
    """ Returns the eigenbasis of the Hamiltonian for a specific value of the transverse field """
    return hamiltonian_cont.eigh(time=hx)

def compute_h_set(hmin, hmax, dh):
    """ Computes the different values of hx given the maximum and minimum values specified by the user """
    return np.arange(hmin, hmax+1e-6, dh)

def update_hx(time=0, hx = None, hx_idx = None):
    """ Updates the protocol hx(t) at time t. The new value is hx.
    One can either specify a scalar value for the hx field. Another option
    is to use the integer index for the field. Since we are hx can take only
    a discrete set of values between hmin and hmax, those values can are also indexed by integers
    """
    if hx_idx is not None:
        hx_discrete[time]=hx_idx
    elif hx is not None:
        idx = np.argmin(np.abs(h_set-hx))
        hx_discrete[time] = idx
    else:
        assert False, "Error in update_hx in Hamiltonian class"

def evaluate_H_at_hx(hx = 0.):
    """ Returns the full hamiltonian evaluated at global transverse field hx """
    return hamiltonian_cont(time = hx)

hamitonian()

[[-1.5 -2.  -2.   0. ]
 [-2.   0.5  0.  -2. ]
 [-2.   0.   0.5 -2. ]
 [ 0.  -2.  -2.   0.5]]


## HO CAZIATO H, (SONO SCARSO)

In [56]:
from Qmodel import compute_H_and_LA
hamiltonian = compute_H_and_LA(L=2, g=1, field=4)["H"]
np.array(hamiltonian,dtype="float")

C:\Users\GUIDA\anaconda3\envs\monti\lib\site-packages\ipykernel_launcher.py:3: ComplexWarning: Casting complex values to real discards the imaginary part
  This is separate from the ipykernel package so we can avoid doing imports until


array([[-0.75, -2.  , -0.  , -0.  ],
       [-2.  ,  0.75, -0.  , -0.  ],
       [-0.  , -0.  , -0.25, -2.  ],
       [-0.  , -0.  , -2.  ,  0.25]])

In [64]:
H1=np.kron(sigma_z,sigma_z)
H2=np.kron(sigma_z,np.identity(2))
H3=4*np.kron(sigma_x,np.identity(2))
H4=np.kron(sigma_z,sigma_z)
H5=np.kron(np.identity(2),sigma_z)
H6=4*np.kron(np.identity(2),sigma_x)
H11= H1+H2+H3+H4+H5+H6
print(-H11)

[[-1.5 -2.  -2.  -0. ]
 [-2.   0.5 -0.  -2. ]
 [-2.  -0.   0.5 -2. ]
 [-0.  -2.  -2.   0.5]]


In [62]:
np.identity(2)

array([[1., 0.],
       [0., 1.]])

In [61]:
field=4
#pauli matrices
sigma_x=1/2*np.array([[0,1],[1,0]])
#sigma_y=np.array([[0,-1j],[1j,0]], dtype=complex) # INUTILE
sigma_z=1/2*np.array([[1,0],[0,-1]])
sigma_z_interaction= np.kron(sigma_z,sigma_z)

#create the hamiltonian according to the number of qubits
L=2
H1 = np.zeros((2**L,2**L))
H2 = np.zeros((2**L,2**L))
H3 = np.zeros((2**L,2**L))

for j in range(L-1):   
    H1 = np.kron(np.identity(2**j),sigma_z_interaction)
    H1 = np.kron(H1,np.identity(2**(L-j-2)))

for j in range(L):
    H3 = np.kron(np.identity(2**j),sigma_x)
    H3 = np.kron(H3,np.identity(2**(L-j-1)))
    H2 = np.kron(np.identity(2**j),sigma_z)
    H2 = np.kron(H2,np.identity(2**(L-j-1)))

H = -(H1 + H2 + field*H3)
print(H)

[[-0.75 -2.   -0.   -0.  ]
 [-2.    0.75 -0.   -0.  ]
 [-0.   -0.   -0.25 -2.  ]
 [-0.   -0.   -2.    0.25]]


## TUTORIAL QUSPIN 

http://weinbe58.github.io/QuSpin/generated/quspin.basis.spin_basis_1d.html

In [43]:
##### define model parameters #####
L=2 # system size
J=1.0 # spin interaction
g=0.809 # transverse field
h=0.9045 # longitudinal field
##### define periodic drive #####
Omega=4.5 # drive frequency
def drive(t,Omega):
	return np.cos(Omega*t)
drive_args=[Omega]
#
##### construct basis in the 0-total momentum and +1-parity sector
basis=spin_basis_1d(L=L,a=1)
# define PBC site-coupling lists for operators
x_field=[[g,i] for i in range(L)]
z_field=[[h,i] for i in range(L)]
J_nn=[[J,i,(i+1)%L] for i in range(L)] # PBC
# static and dynamic lists
static=[["zz",J_nn],["z",z_field]]
dynamic=[["x",x_field,drive,drive_args]]
###### construct Hamiltonian
H=hamiltonian(static,dynamic,static_fmt="dia",dtype=np.float64,basis=basis)
print(H.toarray())

Hermiticity check passed!
Symmetry checks passed!
[[ 3.809  0.809  0.809  0.   ]
 [ 0.809 -2.     0.     0.809]
 [ 0.809  0.    -2.     0.809]
 [ 0.     0.809  0.809  0.191]]
